import "server-only";

import { createHash } from "node:crypto";
import { get0GStorageEnv } from "@/lib/utils/env";

type PublishJsonInput = {
  filename: string;
  data: unknown;
};

export type Publish0GResult = {
  ok: boolean;
  mode: "real" | "mock";
  rootHash?: string;
  txHash?: string;
  sizeBytes: number;
  error?: string;
};

type ConnectivityResult = {
  ok: boolean;
  label: string;
  error?: string;
};

export type ZeroGDiagnostics = {
  mode: string;
  sdkStatus: ConnectivityResult;
  rpcConnectivity: ConnectivityResult;
  indexerConnectivity: ConnectivityResult;
  uploadTest: Publish0GResult | null;
};

export async function publishJsonTo0G({
  filename,
  data,
}: PublishJsonInput): Promise<Publish0GResult> {
  const json = JSON.stringify(data, null, 2);
  const sizeBytes = new TextEncoder().encode(json).byteLength;
  const env = get0GStorageEnv();

  console.log("0G MODE", env.mode ?? "real");
  console.log("0G RPC", maskUrl(env.rpcUrl));
  console.log("0G INDEXER", maskUrl(env.indexerUrl));

  if (env.mode === "mock") {
    return createMockResult({
      filename,
      json,
      sizeBytes,
      error: "Explicit OG_STORAGE_MODE=mock.",
    });
  }

  if (!env.enabled) {
    return {
      ok: false,
      mode: "real",
      sizeBytes,
      error: "OG_STORAGE_ENABLED must be true for real 0G publishing.",
    };
  }

  if (!env.hasRequiredRealConfig || !env.rpcUrl || !env.indexerUrl || !env.privateKey) {
    return {
      ok: false,
      mode: "real",
      sizeBytes,
      error:
        "Missing 0G configuration. Set OG_STORAGE_RPC_URL, OG_STORAGE_INDEXER_URL, and OG_STORAGE_PRIVATE_KEY.",
    };
  }

  try {
    console.log("UPLOAD START");
    const [{ Indexer, MemData }, { ethers }] = await Promise.all([
      import("@0gfoundation/0g-storage-ts-sdk"),
      import("ethers"),
    ]);
    const bytes = new TextEncoder().encode(json);
    const file = new MemData(bytes);
    const [tree, treeError] = await file.merkleTree();

    if (treeError) {
      throw treeError;
    }

    console.log("ROOT HASH", tree?.rootHash());

    const provider = new ethers.JsonRpcProvider(env.rpcUrl);
    const signer = new ethers.Wallet(env.privateKey, provider);
    const indexer = new Indexer(env.indexerUrl);
    const [uploadResult, uploadError] = await indexer.upload(
      file,
      env.rpcUrl,
      signer,
    );

    if (uploadError) {
      throw uploadError;
    }

    const result = uploadResult as Record<string, unknown>;
    const rootHash =
      readString(result.rootHash) ?? readStringArrayValue(result.rootHashes);
    const txHash =
      readString(result.txHash) ?? readStringArrayValue(result.txHashes);

    if (!rootHash) {
      throw new Error("0G upload succeeded without a root hash.");
    }

    console.log("UPLOAD SUCCESS");
    console.log("ROOT HASH", rootHash);

    return {
      ok: true,
      mode: "real",
      rootHash,
      txHash,
      sizeBytes,
    };
  } catch (error) {
    console.error("UPLOAD FAILED", error);

    return createMockResult({
      filename,
      json,
      sizeBytes,
      error: error instanceof Error ? error.message : "0G upload failed.",
    });
  }
}

export async function get0GDiagnostics({
  runUploadTest = false,
}: {
  runUploadTest?: boolean;
} = {}): Promise<ZeroGDiagnostics> {
  const env = get0GStorageEnv();
  const sdkStatus = await checkSdkStatus();
  const [rpcConnectivity, indexerConnectivity] = await Promise.all([
    checkRpcConnectivity(),
    checkIndexerConnectivity(),
  ]);
  const uploadTest = runUploadTest
    ? await publishJsonTo0G({
        filename: "lyra-0g-debug-upload.json",
        data: {
          protocol: "LYRA_0G_DEBUG",
          createdAt: new Date().toISOString(),
          message: "Small 0G Storage connectivity test generated by LYRA.",
        },
      })
    : null;

  return {
    mode: env.mode ?? (env.enabled ? "real" : "disabled"),
    sdkStatus,
    rpcConnectivity,
    indexerConnectivity,
    uploadTest,
  };
}

async function checkSdkStatus(): Promise<ConnectivityResult> {
  try {
    const sdk = await import("@0gfoundation/0g-storage-ts-sdk");
    const hasRequiredExports = Boolean(sdk.Indexer && sdk.MemData);

    return {
      ok: hasRequiredExports,
      label: hasRequiredExports
        ? "SDK loaded: Indexer and MemData available"
        : "SDK loaded but required exports are missing",
    };
  } catch (error) {
    return {
      ok: false,
      label: "SDK import failed",
      error: formatError(error),
    };
  }
}

async function checkRpcConnectivity(): Promise<ConnectivityResult> {
  const env = get0GStorageEnv();

  if (!env.rpcUrl) {
    return { ok: false, label: "RPC URL missing" };
  }

  try {
    const { ethers } = await import("ethers");
    const provider = new ethers.JsonRpcProvider(env.rpcUrl);
    const network = await provider.getNetwork();

    return {
      ok: true,
      label: `Connected to chain ${network.chainId.toString()}`,
    };
  } catch (error) {
    return {
      ok: false,
      label: "RPC connectivity failed",
      error: formatError(error),
    };
  }
}

async function checkIndexerConnectivity(): Promise<ConnectivityResult> {
  const env = get0GStorageEnv();

  if (!env.indexerUrl) {
    return { ok: false, label: "Indexer URL missing" };
  }

  try {
    const { Indexer } = await import("@0gfoundation/0g-storage-ts-sdk");
    const indexer = new Indexer(env.indexerUrl);
    await indexer.getShardedNodes();

    return {
      ok: true,
      label: "Indexer reachable",
    };
  } catch (error) {
    return {
      ok: false,
      label: "Indexer connectivity failed",
      error: formatError(error),
    };
  }
}

function readString(value: unknown) {
  return typeof value === "string" ? value : undefined;
}

function readStringArrayValue(value: unknown) {
  return Array.isArray(value) && typeof value[0] === "string"
    ? value[0]
    : undefined;
}

function createMockResult({
  filename,
  json,
  sizeBytes,
  error,
}: {
  filename: string;
  json: string;
  sizeBytes: number;
  error?: string;
}): Publish0GResult {
  const hash = createHash("sha256")
    .update(filename)
    .update("\n")
    .update(json)
    .digest("hex")
    .slice(0, 24);

  return {
    ok: true,
    mode: "mock",
    rootHash: `0g_mock_${hash}`,
    sizeBytes,
    error,
  };
}

function maskUrl(value?: string) {
  return value || "missing";
}

function formatError(error: unknown) {
  return error instanceof Error ? error.message : String(error);
}
