import { getAgentMemoryProfile } from "@/lib/lyra/memory";
import type {
  Agent,
  AgentLineage,
  OgProvenanceVersion,
  UserProfile,
} from "@/types";

type BuildAgentDnaCapsuleInput = {
  agent: Agent;
  ownerProfile: UserProfile;
  lineageRows: AgentLineage[];
  parentAgents: Agent[];
  versionNumber?: number;
  previousRootHash?: string;
  versionHistory?: OgProvenanceVersion[];
  storageMode?: "real" | "mock" | "preview";
  publishedAt?: string;
};

export function buildAgentDnaCapsule({
  agent,
  ownerProfile,
  lineageRows,
  parentAgents,
  versionNumber = 1,
  previousRootHash,
  versionHistory = [],
  storageMode = "preview",
  publishedAt = new Date().toISOString(),
}: BuildAgentDnaCapsuleInput) {
  const memory = getAgentMemoryProfile(agent);

  return {
    protocol: "LYRA_AGENT_DNA",
    version: "1.0",
    capsuleVersion: "1.0",
    versionNumber,
    previousRootHash: previousRootHash ?? null,
    versionHistorySummary: versionHistory.map((entry) => ({
      version: entry.version,
      rootHash: entry.rootHash,
      publishedAt: entry.publishedAt,
      mode: entry.mode,
      summary: entry.summary,
    })),
    latestEvolutionSummary:
      memory.evolutionLog[0] ??
      memory.recentInfluences[0] ??
      "No evolution events recorded yet.",
    network: "0G",
    chain: {
      name: "0G Galileo Testnet",
      chainId: 16602,
    },
    storage: {
      provider: "0G Storage",
      mode: storageMode,
    },
    publishedAt,
    agent: {
      id: agent.id,
      name: agent.name,
      type: agent.type,
      topic: agent.topic,
      summary: agent.summary,
      keywords: agent.keywords,
      personalityTraits: agent.personalityTraits,
      visibility: agent.visibility,
      createdAt: agent.createdAt,
      updatedAt: agent.updatedAt,
    },
    owner: {
      id: ownerProfile.id,
      username: ownerProfile.username,
      displayName: ownerProfile.displayName,
    },
    memory: {
      profile: memory,
    },
    lineage: {
      kind: lineageKind(agent.type),
      sourceAgentId: agent.sourceAgentId ?? null,
      cloneMetadata:
        agent.type === "clone"
          ? {
              cloneOf: agent.avatarConfig.cloneOf ?? agent.sourceAgentId ?? null,
              cloneDepth: agent.avatarConfig.cloneDepth ?? null,
              clonedAt: agent.avatarConfig.clonedAt ?? null,
              originalCreator: agent.avatarConfig.originalCreator ?? null,
            }
          : null,
      mixMetadata:
        agent.type === "mixed"
          ? {
              parentA: agent.avatarConfig.parentA ?? null,
              parentB: agent.avatarConfig.parentB ?? null,
              generatedWorldview: agent.avatarConfig.generatedWorldview ?? null,
              mixedAt: agent.avatarConfig.mixedAt ?? null,
            }
          : null,
      rows: lineageRows.map((row) => ({
        id: row.id,
        childAgentId: row.childAgentId,
        parentAgentId: row.parentAgentId ?? null,
        percentage: row.percentage,
        relationType: row.relationType,
        parentSnapshotName: row.parentSnapshotName ?? null,
        parentSnapshotSummary: row.parentSnapshotSummary ?? null,
        createdAt: row.createdAt,
      })),
      parents: parentAgents.map((parent) => ({
        id: parent.id,
        name: parent.name,
        type: parent.type,
        topic: parent.topic,
        summary: parent.summary,
        keywords: parent.keywords,
        personalityTraits: parent.personalityTraits,
        storageHash: parent.storageHash ?? null,
        createdAt: parent.createdAt,
      })),
    },
    provenance: {
      storage: "0G Storage",
      app: "LYRA",
      description:
        "Agent DNA, memory, and lineage capsule generated by LYRA.",
    },
    lyra: {
      hackathon: "0G Zero Cup",
      capsuleType: "agent_identity_memory_lineage",
    },
  };
}

function lineageKind(type: Agent["type"]) {
  if (type === "mixed") {
    return "mixed from two identities";
  }

  if (type === "clone") {
    return "independent clone";
  }

  return "original identity";
}
